---
- name: install mysql and setup mysql.
  hosts: mysql
  become: yes

  tasks:
    
    - name: install mysql.
      yum:
        name: mysql
        state: present
    
    - name: create database user with name 'k3s' with all database privileges.
      community.mysql.mysql_user:
        name: k3s
        password: "1234567890"
        priv: '*.*:ALL'
        state: present
